### ISSUE TITLE
Incorporate Caitlin's comments and edits on the PDF

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#15]

**Comment by cmacmac** [comment]
In the Conservation and Applied Ecology section of the Results it reads, "*Biodiversity*, a core concept of conservation, replaced the phrase *biological diversity*, which had been in use since the 1960s [@soule1980]." Did we see an immediate turnover of "biological diversity" to "biodiversity" when biodiversity was combined into  a single word in 1985 [@wilson1998]? Or is there a lag in the literature? I think this could be an interesting commentary on how jargon is created.

**Comment by seananderson** [comment]
That's an interesting idea. Here's what it looks like:
![image](https://user-images.githubusercontent.com/19349/59809622-33118480-92b6-11e9-8c7c-61b2c9d7ca15.png)

Here's what the unstandardized number of references looks like:

year | biological diversity | biodiversity
-- | -- | --
1966 | 2 |  
1967 | 5 |  
1968 | 5 |  
1969 | 1 |  
1970 | 3 |  
1971 | 2 |  
1972 | 1 |  
1973 | 2 |  
1974 | 1 |  
1975 | 7 |  
1976 | 1 |  
1977 | 5 |  
1978 | 3 |  
1979 | 3 |  
1980 | 2 |  
1981 | 4 |  
1982 | 12 |  
1983 | 6 |  
1984 | 5 |  
1985 | 27 |  
1986 | 49 | 9
1987 | 162 | 9
1988 | 101 | 32
1989 | 95 | 52
1990 | 75 | 207
1991 | 197 | 355
1992 | 270 | 1049
1993 | 297 | 1270
… | … | …


So it took about 4 years for biodiversity to surpass biological diversity.

I can throw this into the grab bag of supplemental figures if you want to reference it unless you see some way of working it into the existing main figures.

**Comment by cmacmac** [comment]
I think this could go into Fig 5 Conservation and applied ecology n-grams from 1930–2010, either panel a (birth of conservation) or panel b (threats to biodiversity). If it is added to panel b, we could rename that panel something like 'biological diversity, biodiversity, and threats.' 

I can add a sentence to this section referencing the figure.
