### ISSUE TITLE
Go over the .csv term files with a fine-toothed comb

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#19]
- [x] is there anything obvious missing
- [x] are there any sub terms missing (e.g. plural versions, with a space and without a space, ...)
- [x] is the use of umbrella/sub terms consistent across the figures?
- [x] do the panels (and their order) make sense or are there any terms that would be better shuffled around?

You can figure out which data files are being used here: https://github.com/seananderson/ecology-trends/blob/master/analysis/11-plot-panel-groups.R

Look for the `terms_file` lines:
`terms_file = "data/methods-models-genetics2.csv",`

then look for these .csv file here:
https://github.com/seananderson/ecology-trends/tree/master/data

**Comment by SKuebbing** [comment]
I'm going to address all four questions per figure/data set:

data/methods-models-genetics2.csv

Statistical Paradigms:
-	maximum likelihood: Do people abbreviate maximum likelihood as “ML”.
-	AIC: There’s “AICc” that people use in lieu of AIC… include? I know not exactly the same, but people use it exactly the same way…
Hypothesis Testing:
-	confidence interval: Again, should we include “CI” abbreviation here?
-	Significant difference: could also use "significantly different"
Supporting Information:
-	Supplementary material: suggested include "supplemental material", "supplemental materials", "supporting documents", "supporting document"
-	I wonder if “personal communication” has decreased in time? Worth including since there are only two terms for this panel?  I can’t think of any other formats of this 2-gram to include.
-	Is “som” a common abbreviation for supporting online material? Just making sure it’s not a typo. Also, include other abbreviations ("SI", I guess is the only one I can think of).

Genetic fields (would be good to have Mariah or someone who knows more than I to look at these suggestions):
-	I don’t know this field well, but a few terms are only plural in the data but could (I think) also be singular: epigenetic, metagenomic, proteomic, transcriptomic.
-	Conservation genetics: could also use “conservation genomics”
-	Single nucleotide polymorphism: abbreviated as "SNP" or "SNPs"?

**Comment by SKuebbing** [comment]
data/stats-supp.csv

Multilevel models panel:
-	“mixed-effect model”: include abbreviation “MEM” and “MEMs”

**Comment by SKuebbing** [comment]
data/genetics-supp.csv

SK looked at this and no suggested additions/changes, but not in my wheelhouse! Might be worth have a geneticist look too?

**Comment by seananderson** [comment]
Thanks, I'll get most of these in there. I think we haven't included anything less than 3 characters. 2 character terms bring up a lot of OCR/transcription errors.

Indeed "personal communication" is pretty interesting. It shows up in the giant multipanel plots in the supplement now.

**Comment by seananderson** [comment]
(Those multi panel plots for the supplement are a decent place to look to make sure we haven't missed anything big.)

https://www.dropbox.com/sh/dp26b2w5zt83r6p/AAD3UPkReal_YntKSGnYl_o2a?dl=1

**Comment by SKuebbing** [comment]
Great, thanks! good idea!  And, got it on the <3 characters bit.

**Comment by SKuebbing** [comment]
data/conservation-human-impacts.csv


Threats to biodiversity Panel:
-	Did you consider including “global change” as either a synonym to “climate change” (which I realize it is not really, but I think people use it that way even though it’s broader than just climate change) or as it’s own stand-alone term (so add a 6th term to the figure)?
-	“overexploitation”: what about including “overharvest”?
-	“Invasive species”: suggested to add all of these following terms (there is not a standard, universally-accepted terminology for invasion and all of these terms are used interchangeably with “invasive species”!): “exotic”, “exotic species”, “exotics”, “alien”, “aliens”, “alien species”, “nonnative”, “non-native”, “nonnatives”, “non-natives”, “nonnative species”, “non-native species”, [note: if people feel this is too many terms for this category then I’d like to include more explicitly in the text that we only looked at the primary term “invasive species” and are not including other terms]
-	“habitat loss”: consider including “land conversion”, “habitat conversion”, “habitat destruction”, “habitat degradation”, “land-use change”, land use conversion”, “land-use conversion”, “land conversion”.

Climate Change Impacts panel:
-	“range shifts”: could also include “range expansion”, “range expanding [species]”, “range-expansion”, “range-expanding”, “elevation shift”, “elevational shift” “upward shift”, “upwards shift”, “habitat decline”, “range decline”
o	Also, subpoint here:  I think of phenological shifts as different than range shifts. A plant may flower 10 days early in the year in 2020 than in 1900, but it may have the same range as in 2020.  Likewise, a plant may NOT shift its phenology and may instead shift its entire range to keep its same phenology. Maybe this is an animal/plant distinction? But, I suggest to make “phenological shift” it’s own gram_canonical with the following synonyms: “phenology change”, “phenological change”, “phenology shift”, “phenology mismatch”, “phenological mismatch”, “phenology asynchrony”, “phenological asynchrony”, “phenological disruption” “phenology disruption”
-	“ozone”: maybe “ozonosphere”
-	“sea level rise”
o	You have “sea level rise” twice?
o	Suggested additions: “ocean level rise”, “sea level change”
-	“regime shift”: is “alternative state” and “alternative stable state” used as synonyms here?


Consequences to species/landscapes panel:
-	“habitat fragmentation”: “habitat patchiness”, “habitat connectivity”
-	“deforestation”: “clearcutting”, “deforest”
o	Also, people are using terms like “afforestation” and “reforestation” to counteract deforestation.. Probably shouldn’t be included here, but just a thought. Could also be included as “restoration” terms?
-	 “urbanization”: “urban expansion”, “urban sprawl”, “urban growth”



Species/resource exploitation panel:
-	“fishing”: “over-fishing”
-	Harvesting: “over-harvest”, “over-harvesting”, “overcollection”, “over-collection”, “over-collecting” (could change gram to harvesting and collecting).
-	“hunting”: “over-hunting”
-	“logging”: “clearcutting”, “clear-cutting”, “clear cutting”
-	“mining”: “mineral extraction”, “drilling” (maybe too broad)

Other terms: “fracking” (could go with “mining”?)—but also maybe an increased rise in recent times so on its own?

Geographic protection panel:
-	“park”: “parkland”

**Comment by SKuebbing** [comment]
data/social-ngram.csv

-	Ok, again not my wheel-house so I defer to Diogo and David on this. However, here are some general terms that I come across that we could include in their own right or maybe nested within other terms?
o	Environmental justice (maybe another term in the intervention or well-being panel?)
o	Environmental rights, environmental right (within human well-being panel “human rights” term)


Interventions panel:
-	“certification”: also could include “LEED” or “green building” or ”sustainable building” ?
-	What about these other intervention to include?: 
o	“debt-for-nature swap” (also, “dept for nature” “debt for nature swap”, “debt for nature swaps”, “debt-for-natureswap”, “debt-for-nature swaps”
o	Sustainable development as another type of intervention: also include “green building”, “sustainable building”, 
o	“payment for ecosystem services”, “PES”, “payment for environmental services”

**Comment by SKuebbing** [comment]
Sean - I still need to do the following: (1) close look at "ecology_panels_10_05.csv" file with suggestions AND then after I'm familiar with all of our terms I'll closely look at the decadal giant panels to see if there are any terms that pop out at me.  Will do tonight or tomorrow.  Then, I think I've done all I can with this part!

**Comment by SKuebbing** [comment]
Okay, here are comments on community ecology panels (also cross-referenced with the decadal giant figures:

data/ecology_panels_10_05.csv
Scale panel:
-	None of the terms have their plural form?  Was that intentional? If not, plurals to add are the following: “genes”, “cells”, “populations”, “organisms”, “communities”, “ecosystems”, “metapopulations”
-	Should probably also in “landscape” and “individual” within the scale panel as its own umbrella term (with “landscapes” and “individuals” as plural).  Both of these were in the decadal giant 2000-2010 term list as a top term, and “individual” was a top term for all four deacadal periods.
-	If you look at a typical ecology text book, the “top” scale includes “biomes” and “biosphere”. Since this panel has a lot of terms, I suggest to include biosphere as its own term; biome I could go either way -- could potentially be lumped with “ecosystem” but they are slightly different—since it’s not a top 150 term in any decadal grouping, we could also just leave it off.
-	“organism”: along with plural, could also include “organismal”? but maybe that is
-	“metapopulation”- there are also “metacommunities”.  Neither metapopulation or metacommunity are in decadal giants; could lump them together as a “meta” scale (with plurals) or leave out.

Scale without ‘species’ panel
-	Same comment as above…

Species Interactions panel:
-	Do we need to include other forms of the current terms (adjectives, nouns of the species?) we have?
o	“predation”, could also include “predatory”, “predator”, “predators”
o	“competition” could also include “competitive”, “competitor”, “competitors”
o	“parasitism” could also include “parasitic”, “parasite”, “parasites”
o	“mutualism” could also include “mutualistic”, “mutualist”, “mutualists”

-	(note: I realize I’m suggesting a lot of changes to this panel in terms of term additions and/or changes; if you like them I agree to work on adjusting the text to accommodate changes:
o	I’d like to include “facilitation” on the panel as its own term.  Regardless of whether it’s starting to peak or compensate for the decrease in “competition”, it’s the natural opposite of “competition”. 
o	Other interactions we could include: “herbivory”, “pollination”;  if it’s too many terms then it’s legit to put “parasitism” and “herbivory” as alternative terms for “predation” and “pollination” as alternative term for “mutualism”.  These are all examples of either predatory or mutualistic relationships.
o	The opposite of a “commensalism”  is “amensalism”… I feel if we include one we should include it’s analog.
o	Recognizing that this IS a “species interaction” panel, there is rapid growth/interest in the study of the relative importance of “intraspecific” interactions compared to “interspecific” interactions.  I wonder what that comparison would look like, and if it’s worth including both terms here, or as a supp panel
-	With the exception of the term “competition”, that was in the top 144 terms in the 1980-1999 decadal panels, none of the other terms we have in the graph or the ones I’m suggesting are “top” terms across the decades. “interspecific competition” came up in the 60s-70s and 80s-90s as a top 2-gram, but before or after.

Theories panel:
-	Is “theory of natural” the “theory of natural selection”?  While I know 4-grams are out, selection is a top 144 term starting in 1980s on…, likely related to theory of natural selection. Should we then include as other terms here “of natural selection” and “natural selection”? (natural selection was dominant 2 gram, and selection dominant 1-gram)
-	“theory of island” – should we also include “of island biogeography”?
-	I’m not sure there’s a good way to hand-select theories (there are so many). I relied on the “decadal giants” to guide me here: here are terms that came out in top 144 for certain decade timespans that could fit here:
o	“evolutionary theory” – also include “evolution”
o	 “metabolic theory” isn’t in the decadal giant 1-gram or 2-grams, but also a pretty dominant theory? “metabolic rate” does come up in 2-grams in the 80s
o	“coexistence theory” – never top 1-gram or 2-gram

Hypothesis panel:
-	“null hypothesis” comes up in the decadal giant 2-grams in the 80s.
-	Interesting note “hypothesis doesn’t make its way into the top 1-rams until the 80s. Worth putting just that word by itself (with “hypotheses”) to demonstrate that ecology has become a more hypothesis-driven science? Also “mechanism” has the same trend. See comment below about “Scientific method” panel.

**Comment by SKuebbing** [comment]
I went through the decadal giants panels (both 1-grams and 2-grams) and the following things popped out at me; some in relation to our current panels (more additions) and some just some interesting patterns I saw in the data.

NOTES FROM STUDYING DECADAL Giants

For 1-grams, these terms were top terms in all 4 periods. I’ve added suggested areas to include them…if we want to capture them in the main text:
-	“region”, could add to “scale” panel for community ecology. Maybe too vague a term?

For  1-grams, these terms popped up as popular in the last period, but not prior

-	“Parameter” add as a term in the Models for inference panel (Methods Figure)?
-	“Probability” add as a term in the Hypothesis testing panel (Methods Figure)?
-	“Variable” add as a term in the Models for inference panel (Methods Figure)?

SCIENTIFIC METHOD
-	What about a Scientific Methods panel?  Don’t know where it would fit, but some interesting patterns with single terms happending in decadal giants that fit this idea:
o	“Observation” (top 144 for first three periods, NOT in the fourth; linkes to idea that we’re losing natural history and not making observations?)
o	“Hypothesis”: become a top 144 term in the 3rd period (80s) and not commonly used before then.
o	“Experiment”: top 144 term for all four decadal periods
o	“Data”: top 144 term for all four decadal periods; “analysis”: top 144 term for all four decadal periods
o	“conclusion” – never a top term in any period??? 


BIOGEOGRAPHIC BIASES:
“USA” becomes a top 1-gram in the last two periods. Does this demonstrate the dominance of publications coming out of the US in ecological literature; or does it mean that JSTOR is biased?

towards US publications (for example, if all the ESA jouranls are in JSTORE but not BES that could create the bias; not that an American can’t publish in BES and vice versa….). Along these same lines, “costa rica” and “puerto rico” come up as regions in the 2-grams in the 60s. sort of interesting? North Carolina is a top term in the 00s? north America is top term throughout. Future paper on WHERE we do ecology in the making….

I suggested above including “personal communication” with the Supporting Information panel of the methods figure. It does come up as a top 2-gram in the 60s-90 decadale panels, with a steep drop in the last period.  Also interesting is “phd thesis” with a very similar trend; we don’t cite theses or personal comm, we just put stuff online to support our arguments.

ECOLOGICAL SUBDISCIPLINES
There are a lot of subdisciplines of ecology that pop up in the 2-grams starting in the 60s – and ecology as a 1-gram has an interesting trajectory.  Might be worth considering a “subfields of ecology” panel?  Also don’t know where this would go…
-	“biological sciences” is top term periods 2-4
-	“biological conservation” becomes a top term in period 4
-	“animal ecology” arises in period 3 (80s)
-	“functional ecology” arises in period 3 (80s)
-	“holarctic ecology” arises in period 3 (80s)
-	“marine biology” arises in period 3 (80s)
-	“population biology” arises in period 3 (80s)
-	“evolutionary biology” arises in period 4 (00s)
-	“global ecology” arises in period 4 (00s)

**Comment by seananderson** [comment]
Notes from Skype (written by Paul):

Threats to biodiversity panel:
- considered global change, but didn't include because of journal title
- include 'overharvest' in 'overexploitation'
- throw other 'invasive' terms into new supplemental (lump together by root), add language to text pointing to this panel
- include terms with habitat loss

Climate change panel:
- include 'elevation/al shift', 'upward/s shift' with 'range shifts'
- include 'habitat decline', 'range decline' with 'habitat loss' (threats to biodiversity)
- add terms related to phenology as new to climate change panel with all terms mentioned grouped
- include 'ozonosphere' with 'ozone
- correct 'sea level rise'
- add 'ocean level rise' and 'sea level change' to 'sea level rise'
- include 'alternative (stable) state' with 'regime shift'

Consequences to species/landscapes panel:
- include 'habitat patchiness' with 'habitat fragmentation'
- include 'clearcutting/clearcut' with 'deforestation'
- move 'restoration' to panel f, include 'afforestation' and 'reforestation' with 'restoration'
- include all terms with 'urbanization'

Species/resource exploitation panel:
- include overfishing, overharvesting, overhunting, overcollecting with harvesting, change to 'harvesting and collecting'
- add terms to 'logging'
- add 'fracking' with 'mining'

Geographic protection panel:
- add 'parkland' to 'park'

Social panels:
- send for review to David and Diogo

Ecology panels:
- add plurals and rerun
- add 'landscape' (individual too broad) to panel a and b
- check time series for 'biome', 'biosphere', and 'ecoregion' (which could be combined with biome), and add winner to panel
- drop metapopulation

Species interactions panels:
- include 'predatory/competitive/parasitic/mutualistic interaction'
- add 'facilitation' and 'facilitative interaction'
- drop 'commensalism'
- add 'intra/interspecific interactions' as supplement

Theories panel:
- label on panel should be 'theory of natural [selection]' and 'theory of island [biogeography]'
- add sentence or two about data-driven nature of theories panel
- verify current method for 'theory' and 'hypothesis' panels and consider using Fig. S2 method instead

Hypothesis panel:
- just mention 'hypotheses' trends in text as ecology becoming data-driven science

Decadal giants:
- add 'parameter' to models panel ('probability' and 'variable' too vague)
- add new scientific method panel to supplement (don't include 'conclusion') with plural and singular versions
- add 'personal communication' to supporting information panel
- no to PhD thesis

General notes:
- remove all journal titles from 2-grams
- remove british columbia and USA from supplemental figures
- remove society
- remove other species from Fig 1
- remove many case, upper part, such case, different type, other animal, right angle, more rapid, more likely, small amount, other factor, puerto rico, high level, more important, north american (place names in general), forest service, previous study, total number from supplemental figures
- add other journals to Table S1 that were culled

**Comment by seananderson** [comment]
Thanks! After a group call to make some hard decisions, I started implementing the changes here https://github.com/seananderson/ecology-trends/commit/092adf8cccc8107a5fffb8d0a19ff62ad717b156

I implemented the changes down to the comments about "logging”: “clearcutting”, “clear-cutting”, “clear cutting”

Need to come back to this.
