### ISSUE TITLE
Consider restructuring the introduction

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#23]
- It could potentially use another lead-in paragraph building more on what has been done before and where the gap is.
- There are multiple ways it could start. Perhaps there is a stronger way?

**Comment by SKuebbing** [comment]
This is the new text I added from the conflicted version... if you like it then I can tackle the discussion if you want (merging themes).

The field of ecology has experienced rapid growth since the discipline-specific journal, *Ecology*, was first published over a century ago [@reiners2017; @kim2018]. Today, hundreds of ecology journals represent numerous subdisciplines span in scope from theoretical to applied. It is potentially no surprise that the field is today had diverged into many distinct subdisciplines; although there is much disagreement about the origins and emergence of ecology as its own unique scientific discipline, most scholars  agree that "ecology" arose at some point in the late 19th or early 20th century drawing from a broad selection of academic studies including geography, geology, evolutionary biology, systematics, physiology, natural history, and natural resource management (@Simberloff 1980; @Edgerton1983; @Kingsland 2005, @Ayres2012, @Huston2016).

Some of the fastest growing subdisciplines in ecology fall under the umbrella of "applied ecology" and focus on the conservation, protection, and management of rapidly diminishing natural resources, ecosystems, and plant and animal populations (@Staples2019; @Li2011; @Lockwood2013; @Griffiths2012). This is likely owing to the mounting evidence of the scale and magnitude of the impact of human populations on global biogeochemical cycles, species extinction rates, and habitat conversion (@Staples2019; @Li2011; @Lockwood2013; @Griffiths2012; @Young2005; @Simberloff 2011). A danger for any rapidly growing field of study is that researchers can quickly become "siloed" into their own subdiscipline camps, forming their own jargon, missing key conceptual bridges, and squandering potential opportunities for interdisciplinary collaborations (@Staples2019; @Margles2010).  This academic path is especially worrisome for applied ecological research because of the urgency for scientifically-sound data to inform conservation and management decisions (cite IPBES summary report and latest IPCC report). 

In light of such rapid growth and diversification, synthesizing larger trends in a field can be challenging. Yet, broad overviews can be critical for bridging siloed disciplines and highlighting key concepts that potentially span multiple subdisciplines. Additionally, syntheses can guide new research, inform funding directions, and structure educational frameworks [@mccallen2019]. The discipline of culturomics---the quantitative analysis of large bodies of text---offers a rich framework with which to track the evolution of a field through time [@michel2011; @ladle2016] and highlight areas of convergence across subdisciplines. Specifically, word use in the published literature can serve as a proxy for tracking realized, versus perceived, importance of fundamental concepts and terms. This approach has been successfully applied to smaller subsets of the ecological literature, notably a century of titles and abstracts in the journal *Ecology* [@kim2018], automated content analysis of titles and abstracts in top ecology journals based on impact factor [@mccallen2019], and more specific research questions restricted to certain regions or taxa [e.g., @beale2018, @Correia2018].

Here, we build on previous analyses [e.g., @carmel2013; @reiners2017; @kim2018; @mccallen2019] by providing the first full-text analysis of ecology and conservation journals over eight decades encompassing `r n_journals` journals, 131,533 articles, and over half a billion words. We base our analysis on the JSTOR full-text corpus of "n-grams" from 1930 to 2010--the period of time with the most robust journal coverage in the JSTOR database--for all journals that regularly publish ecological or conservation papers and are not regionally or taxonomically exclusive (see Methods). Our approach allows us to scan a larger number of journals and texts and reduce bias in our selection of terms or words.  An n-gram is a sequence of terms separated by a space. For example, "biogeography" is a 1-gram and "body size" is a 2-gram (we herein denote n-grams in italics). We standardize n-gram frequency by total words per year and analyze trends over time for a selection of n-grams. We derive our n-gram selection through both algorithmic and hand-curated approaches: (1) drawing on the most frequent and rapidly growing/declining n-grams in various decades and (2) developing logical groupings of terms that fall under key ecology and conservation themes (see Methods).
