### ISSUE TITLE
Add more conservation to introduction

### ISSUE THREAD

**Issue by seananderson** [seananderson/ecology-trends#30]
Given the title and the focus on conservation in the figures and discussion, we should probably balance the introduction a bit more towards conservation than it currently is.

- could highlight "applied ecology" as "conservation"

Also:
Do we have room to get into conservation origins? Like cite cons origin in game preservation/public lands and how ecology + conservation = applied ecology? Maybe a paragraph? Not sure if there is space for this?

**Comment by SKuebbing** [comment]
See my rewrite on the Introduction. I read some history of science publications on the history of ecology, and most folks attribute the rise of ecology to the merging of many fields, including natural history and game management (think Leopold), which also could be argued to be the origins of conservation biology. So, I reworked the introduction a bit to frame the paper that it's more like ecology is "retuning to its roots" rather than taking this drastic shift towards a new area of study (applied ecology).  I don't know if this gets at what you're looking for, but I'm happy to edit and change focus to more of the birth of conservation biology as a discipline.
